export const kSymSpace           =  32;    // space
export const kSymBorder          =  97;    // border
export const kSymDirt            =  98;    // dirt
export const kSymDirtFace        =  99;    // Dirt E. Face
export const kSymDirtFaceRight   = 100;    // Dirt E. Face
export const kSymDirtFaceLeft    = 101;    // Dirt E. Face
export const kSymButterfly       = 102;    // butterfly
export const kSymGuard           = 103;    // guardian
export const kSymDiamondExplode  = 104;    // diamond explosion
export const kSymDiamondExplode2 = 105;    // diamond explosion
export const kSymSpaceExplode    = 106;    // space explosion
export const kSymSpaceExplode2   = 107;    // space explosion
export const kSymAmoeba          = 108;    // amoeba
export const kSymMagicWall       = 109;    // magic wall
export const kSymEgg             = 110;    // monster egg
export const kSymEggWiggle       = 111;    // egg wiggle
export const kSymEggHatch        = 112;    // egg hatch
export const kSymEggOpen         = 113;    // egg opening
export const kSymWall            = 120;    // wall
export const kSymDiamond         = 121;    // diamond
export const kSymRock            = 122;    // rock
