export const kSymSpace           = 0x0000;    // space
export const kSymBorder          = 0x0001;    // border
export const kSymDirt            = 0x0002;    // dirt
export const kSymDirtFace        = 0x0003;    // Dirt E. Face
export const kSymDirtFaceRight   = 0x0004;    // Dirt E. Face
export const kSymDirtFaceLeft    = 0x0005;    // Dirt E. Face
export const kSymButterfly       = 0x0006;    // butterfly
export const kSymGuard           = 0x0007;    // guardian
export const kSymDiamondExplode  = 0x0008;    // diamond explosion
export const kSymDiamondExplode2 = 0x0009;    // diamond explosion
export const kSymSpaceExplode    = 0x000A;    // space explosion
export const kSymSpaceExplode2   = 0x000B;    // space explosion
export const kSymAmoeba          = 0x000C;    // amoeba
export const kSymMagicWall       = 0x000D;    // magic wall
export const kSymEgg             = 0x000E;    // monster egg
export const kSymEggWiggle       = 0x000F;    // egg wiggle
export const kSymEggHatch        = 0x0010;    // egg hatch
export const kSymEggOpen         = 0x0011;    // egg opening
export const kSymWall            = 0x0012;    // wall
export const kSymDiamond         = 0x0013;    // diamond
export const kSymRock            = 0x0014;    // rock
